#!/bin/bash

set -e

read -p "Are you sure you want to reset the game? (y/n): " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 1
fi

APP_ID=com.github.avojak.paint-spill
GSETTINGS_ID=$APP_ID
GSETTINGS_PATH=$APP_ID

print_setting () {
    echo -e "  $1 = $(flatpak run --command=gsettings $GSETTINGS_ID get $GSETTINGS_PATH $1)"
}

set_setting () {
    flatpak run --command=gsettings $GSETTINGS_ID set $GSETTINGS_PATH $1 "$2"
    print_setting $1
}

echo
echo "Resetting GSettings..."

set_setting pos-x 360
set_setting pos-y 360
set_setting difficulty 1
set_setting first-launch true
set_setting is-game-in-progress false
set_setting board-state ""
set_setting moves-remaining 0
set_setting num-games-won 0
set_setting num-games-lost 0

echo
echo -e "\033[1;32mDone\033[0m"
echo